from loom.acp import AcpCallTool, AcpConfig
from loom.auth import (
    ApiKeyHeaderApplier,
    ApiKeyStringApplier,
    Applier,
    AuthApplierError,
    BasicHttpApplier,
    BearerHttpApplier,
    CredentialDenied,
    CredentialPolicy,
    CredentialResolver,
    GateDecision,
    JwtBearerApplier,
    MissingPrincipalError,
    NoApplierError,
    OAuth2CCHttpApplier,
    PolicyEnforcer,
    PolicyMode,
    PolicyStore,
    ScopeAccessDenied,
    ScopeAcl,
    ScopeNotFoundError,
    SecretExpiredError,
    SigV4Applier,
    SshConnectArgs,
    SshKeyApplier,
    SshPasswordApplier,
)
from loom.heartbeat import (
    HeartbeatDriver,
    HeartbeatEvent,
    HeartbeatManager,
    HeartbeatRecord,
    HeartbeatRegistry,
    HeartbeatRunRecord,
    HeartbeatScheduler,
    HeartbeatStore,
    HeartbeatToolHandler,
    RunFn,
    Schedule,
    is_due,
    load_heartbeat,
    make_run_fn,
    parse_schedule,
)
from loom.hitl import (
    CURRENT_SESSION_ID,
    TIMEOUT_SENTINEL,
    BrokerAskUserTool,
    HitlBroker,
    HitlEvent,
    HitlRequest,
)
from loom.home import AgentHome
from loom.llm.base import LLMProvider
from loom.llm.registry import ProviderRegistry
from loom.loop import Agent, AgentConfig, AgentTurn
from loom.mcp import McpClient, McpServerConfig, McpToolHandler
from loom.permissions import AgentPermissions
from loom.prompt import PromptBuilder, PromptSection
from loom.runtime import AgentRuntime
from loom.skills.guard import SkillGuard
from loom.skills.manager import SkillManager
from loom.skills.registry import SkillRegistry
from loom.skills.types import Skill, SkillGuardVerdict, SkillMetadata
from loom.store.keychain import KeychainStore
from loom.store.memory import MemoryEntry, MemoryStore
from loom.store.secrets import (
    ApiKeySecret,
    AwsSigV4Secret,
    BasicAuthSecret,
    BearerTokenSecret,
    JwtSigningKeySecret,
    OAuth2ClientCredentialsSecret,
    PasswordSecret,
    Secret,
    SecretMetadata,
    SecretsStore,
    SecretStore,
    SshPrivateKeySecret,
)
from loom.store.vault import FilesystemVaultProvider, VaultProvider
from loom.tools.base import ToolHandler, ToolResult
from loom.tools.registry import ToolRegistry
from loom.tools.ssh import SshCallTool
from loom.tools.vault import VaultToolHandler
from loom.types import (
    ChatMessage,
    ChatResponse,
    ContentDeltaEvent,
    DoneEvent,
    ErrorEvent,
    LimitReachedEvent,
    Role,
    StopEvent,
    StopReason,
    StreamEvent,
    ToolCall,
    ToolCallDeltaEvent,
    ToolExecResultEvent,
    ToolExecStartEvent,
    ToolSpec,
    Usage,
    UsageEvent,
)

__version__ = "0.3.0"

__all__ = [
    # auth — Phase A
    "Applier",
    "BasicHttpApplier",
    "BearerHttpApplier",
    "OAuth2CCHttpApplier",
    "ApiKeyHeaderApplier",
    "ApiKeyStringApplier",
    "CredentialResolver",
    "AuthApplierError",
    "SecretExpiredError",
    "NoApplierError",
    "ScopeNotFoundError",
    # auth — Phase B
    "PolicyMode",
    "CredentialPolicy",
    "PolicyStore",
    "GateDecision",
    "CredentialDenied",
    "PolicyEnforcer",
    # auth — RFC 0003 SSH appliers
    "SshConnectArgs",
    "SshPasswordApplier",
    "SshKeyApplier",
    # auth — Phase C
    "SigV4Applier",
    "JwtBearerApplier",
    "ScopeAccessDenied",
    "MissingPrincipalError",
    "ScopeAcl",
    # store.secrets
    "ApiKeySecret",
    "AwsSigV4Secret",
    "BasicAuthSecret",
    "BearerTokenSecret",
    "JwtSigningKeySecret",
    "OAuth2ClientCredentialsSecret",
    "PasswordSecret",
    "Secret",
    "SecretMetadata",
    "SecretStore",
    "SecretsStore",
    "SshPrivateKeySecret",
    # store.keychain
    "KeychainStore",
    "Agent",
    "AgentConfig",
    "AgentHome",
    "AgentRuntime",
    "AgentTurn",
    "ChatMessage",
    "ChatResponse",
    "ContentDeltaEvent",
    "DoneEvent",
    "ErrorEvent",
    "LimitReachedEvent",
    "LLMProvider",
    "StopEvent",
    "ToolCallDeltaEvent",
    "ToolExecResultEvent",
    "ToolExecStartEvent",
    "UsageEvent",
    "MemoryEntry",
    "MemoryStore",
    "AgentPermissions",
    "PromptBuilder",
    "PromptSection",
    "ProviderRegistry",
    "Role",
    "Skill",
    "SkillGuard",
    "SkillGuardVerdict",
    "SkillManager",
    "SkillMetadata",
    "SkillRegistry",
    "StopReason",
    "StreamEvent",
    "ToolCall",
    "SshCallTool",
    "ToolHandler",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "Usage",
    "VaultProvider",
    "FilesystemVaultProvider",
    "VaultToolHandler",
    "AcpCallTool",
    "AcpConfig",
    "McpClient",
    "McpServerConfig",
    "McpToolHandler",
    "BrokerAskUserTool",
    "CURRENT_SESSION_ID",
    "HitlBroker",
    "HitlEvent",
    "HitlRequest",
    "TIMEOUT_SENTINEL",
    # heartbeat
    "HeartbeatDriver",
    "HeartbeatEvent",
    "HeartbeatManager",
    "HeartbeatRecord",
    "HeartbeatRegistry",
    "HeartbeatRunRecord",
    "HeartbeatScheduler",
    "HeartbeatStore",
    "HeartbeatToolHandler",
    "RunFn",
    "Schedule",
    "is_due",
    "load_heartbeat",
    "make_run_fn",
    "parse_schedule",
]
